package org.transformer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class AdaptiveLayoutTransformerGUI extends JFrame {

    // Automatically generated by Eclipse
    private static final long serialVersionUID = 1L;

    // Components
    // Main panel and radio buttons for layout selection
    private JPanel innerPanel;
    private JRadioButton oneColumnButton, twoColumnButton, threeColumnButton;

    // Inner class for ItemListener to respond to layout changes
    private class LayoutChangeListener implements ItemListener {
        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                // Change layout according to selected option
                if (e.getSource() == oneColumnButton) {
                    innerPanel.setLayout(new GridLayout(0, 1));
                } else if (e.getSource() == twoColumnButton) {
                    innerPanel.setLayout(new GridLayout(0, 2));
                } else if (e.getSource() == threeColumnButton) {
                    innerPanel.setLayout(new GridLayout(0, 3));
                }
                // Update inner panel to reflect changes
                innerPanel.revalidate();
                innerPanel.repaint();
            }
        }
    }

    // Constructor
    public AdaptiveLayoutTransformerGUI(String title) {
        super(title);

        // Set behavior when closing the window
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Set window size
        setSize(400, 300);
        // Center the window on the screen
        setLocationRelativeTo(null);

        // Create inner panel with GridLayout
        innerPanel = new JPanel(new GridLayout(0, 1));
        for (int i = 1; i <= 6; i++) {
            innerPanel.add(new JLabel("Label " + i));
        }

        // Create radio buttons for layout selection
        oneColumnButton = new JRadioButton("1 Column");
        twoColumnButton = new JRadioButton("2 Columns");
        threeColumnButton = new JRadioButton("3 Columns");

        // Add radio buttons to a ButtonGroup
        ButtonGroup layoutGroup = new ButtonGroup();
        layoutGroup.add(oneColumnButton);
        layoutGroup.add(twoColumnButton);
        layoutGroup.add(threeColumnButton);

        // Default selection on Grid Layout
        oneColumnButton.setSelected(true);

        // Add ItemListener to respond to layout changes
        ItemListener layoutChangeListener = new LayoutChangeListener();
        oneColumnButton.addItemListener(layoutChangeListener);
        twoColumnButton.addItemListener(layoutChangeListener);
        threeColumnButton.addItemListener(layoutChangeListener);

        // Create a panel for the radio buttons
        JPanel layoutSelectionPanel = new JPanel();
        layoutSelectionPanel.add(oneColumnButton);
        layoutSelectionPanel.add(twoColumnButton);
        layoutSelectionPanel.add(threeColumnButton);

        // Add components to the main panel
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(layoutSelectionPanel, BorderLayout.NORTH);
        getContentPane().add(innerPanel, BorderLayout.CENTER);

        // Make the window visible
        setVisible(true);
    }
}
